##############################################
#                 GLOBAL                     #
##############################################

ChatDelay: true
#ChatDelay - is responsible for the chat delay, i.e. every how many seconds the player can write, select this option if you want this feature to work

ChatDelayInSeconds: 3
#ChatDelayInSeconds - seconds for ChatDelay
#If Chat Delay is disabled, this doesn't work

ChatFormatting: true
#Permission: 'wow.chat.colorcodes'
#If this option is true, you can use BuiltIn feature: ChatFormatting:
#Your message can be: &7&lChat&b&lFormatting&n!

UnicodeEmojis: true
#Permission: 'wow.chat.unicodeemojis'
#You can use Emojis in chat e.g:
#<3 changing to ❤
#:star: changing to ★
#Full list in https://github.com/opkarol/WoWChat/wiki/Emoji-List

DebugModeLevel: 0
#Feature in progress, this can help me a lot with founding a bugs and helping you guys <3

words: fuck;shit;asshole
#Add here words after ; e.g: a;b;c;d

cancelEvent: true
#Set True, if you want cancel sending message, after saying "words"

AC: #AdminChat
  Enable: true
  Prefix: '@'
#Prefix for AdminChat
#When you change the value of prefix, you must reload or restart your server

##############################################
#                MESSAGES                    #
##############################################


Error: '&c&lERROR >> '
#Prefix for error

Use: '&c&lUsage: &7/chat <off,on,clear,reload,help>'
#This message will show when player(admin) write /chat

Permission: '&7&lYou need %permission% to do it.'
#This message will show when player without permission try /chat

ChatDelayWarn: '&7&lYou can talk again in %seconds% seconds'
#This message will show when player get ChatDelayed
#If Chat Delay is disabled, this doesn't work

YouCantChat: '&7&lYou cant chat, because chat is off'
#This message will show when - /chat off is on, and player without permission: 'wow.chat.bypass.delay' try to talk

GlobalChatTurnOn: '&7&lChat was turned on by: %playerchat%'
#This message will show when you turn on chat - /chat on

GlobalChatTurnOff: '&7&lChat was turned off by: %playerchat%'
#This message will show when you turn off chat - /chat off

ChatTurnOff: '&7You turn off chat'
#This message is showing to you when you turn off chat - /chat off

ChatTurnOn: '&7You turn on chat'
#This message is showing to you when you turn on chat - /chat on

ChatOn: '&7Chat already turned on!'
#This message will show, when player(admin) try to /chat on, but its already turn on

ChatOff: '&7Chat already turned off!'
#This message will show, when player(admin) try to /chat on, but its already turn off

ReloadSuccess: '&7&lConfig reloaded!'
#This message will show, when player(admin) try to /chat reload

ChatClear:
  Line1: ''
  Line2: '&8&l<&m-&r&8&l> &B&lCHAT &8&l<&m-&r&8&l>'
  Line3: '&8&l<&m-&r&8&l> &C&LWAS CLEARED BY: %PLAYER% &8&l<&m-&r&8&l>'
  Line4: '&8&l<&m-&r&8&l> &e&lserver.com &8&l<&m-&r&8&l>'
  Line5: ''
#This lines of message will show when player(admin) try to /chat clear
#You can use BuiltIn placeholders:
#Put '' for blank line
#DONT REMOVE LINES!!!


messages:
  warnadmin: '%PLAYER% writed %MESSAGE%!'
  warnplayer: '&cDont write &7&l%MESSAGE%!'
#This message will show when player try to say bad word from list: 'words'


AdminChat: '&c&lAC &7- &6&l%PLAYER%&7: &f&l%MESSAGE%'
#This message will show when player(admin) try to say: @<message>
##############################################
#              IN NEXT UPDATES               #
##############################################

#I want add this commands in nexts update, please be patient!
AutoMessagesOn:
AutoMessagesInterval:
AutoMessages:
  Text1:
  Text2:
  Text3:
  Text4:
  Text5:
  Text6:

Join:
  enable: false
JoinMessage:
  Join1: '' #Permission: wowchat.custom.Join1, you can give this permission to OWNER, and change to him prefix
  Join2: '' #Permission: wowchat.custom.Join2, you can give this permission to AD,OM, and change to him prefix
  Join3: '' #Permission: wowchat.custom.Join3, you can give this permission to MOD, and change to him prefix
  Join4: '' #Permission: wowchat.custom.Join4, you can give this permission to HELPER, and change to him prefix
  Join5: '' #Permission: wowchat.custom.Join5, you can give this permission to MEMBER, and change to him prefix
Leave:
  enable: false
LeaveMessage:
  Leave1: '' #Permission: wowchat.custom.Leave1, you can give this permission to OWNER, and change to him prefix
  Leave2: '' #Permission: wowchat.custom.Leave2, you can give this permission to ADMIN, and change to him prefix
  Leave3: '' #Permission: wowchat.custom.Leave3, you can give this permission to MOD, and change to him prefix
  Leave4: '' #Permission: wowchat.custom.Leave4, you can give this permission to HELPER, and change to him prefix
  Leave5: '' #Permission: wowchat.custom.Leave5, you can give this permission to MEMBER, and change to him prefix

LocalChat:
  Enabled: true
  Range: 15
  Messages:
    Bypass: '&9You are now bypassing localchat. You can hear them, they can not hear you!'
    NoBypassLonger: '&9You are no longer bypassing localchat.'

GlobalChat:
  Enabled: true
  Start: '!G' #Must be a  UpperCase letter, or special character e.g: #, !, %, & but cant be a '/', or be a doubled e.g: !G, &A, *V
  Prefix: '&8[&3&lGlobal&8]&f&l'
  ColorMessage: '&a'
  Message: '%G_Prefix% %PLAYER%:%G_Color% %MESSAGE%'
  RawConsole:
    Prefix: '[Global]'
#You can use Placeholders from PlaceholderAPI here :)

#kickoncensor: false #Don't work for nowmessages:
#  kick: 'You are kicked for writing "%WORD%!' #Don't work for now

##############################################
#               PLACEHOLDERS                 #
##############################################

# %PLAYER% - use this placeholder for player name
# %MESSAGE% - use this placeholder for player message
# %WORD% - use this placeholder for player word(specific)
# %playerchat% - use this placeholder for player name who chat
# %seconds% - use this placeholder for seconds left from chatdelay
# %permission% - use this placeholder for permission
# PlaceholderAPI: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
# %G_Prefix% - Prefix for Global Chat
# %G_Color% - Color of global chat player's message
##############################################
#                 PLUGIN                     #
##############################################


#         WowChat - inspired by every chat's plugin
#/////////////////////////////////////////////////////////////
#               Created and edited by: OpKarol
#/////////////////////////////////////////////////////////////
#                  All rights reserved
#/////////////////////////////////////////////////////////////
#DON'T CHANGE THIS                           #
ConfigVersion: 'Beta 0.5'
#                                            #
#              BETA ACCESS                   #
#                                            #
#          FREEEEEEEEEEEEEEEEEEEE            #
##############################################
#                   END                      #
##############################################