name: WoWChat
api-version: 1.16
version: 0.5.2
main: me.opkarol.main.opchat
description: WoWChat - THE RPG UPDATE
author: OpKarol
softdepend: [PlaceholderAPI]

commands:
  chat:
  spy:
  channel:

permissions:
  wowchat.bypass:
    description: Bypassing /chat off
    default: op
  wowchat.admin:
    description: The ability to manage the chat
    default: op
  wowchat.bypass.delay:
    description: Bypassing chat delay
    default: op
